-- Backfill missing column defaults for every table in `public`.
--
-- Schema was originally generated by Prisma, which produced identifiers and
-- timestamps at the application layer. After migrating to direct Supabase
-- JS inserts (no ORM), rows omitting `id` / `createdAt` / `updatedAt` fail
-- with NOT NULL violations. This migration:
--   1. Sets `DEFAULT gen_random_uuid()` on every uuid `id` PK column that has
--      no default.
--   2. Sets `DEFAULT now()` on every `createdAt` / `updatedAt` timestamp
--      column that has no default.
--   3. Installs a BEFORE UPDATE trigger on every table with an `updatedAt`
--      column so it auto-advances on writes.
--
-- Idempotent: re-running only targets columns still missing a default and
-- drops+recreates the trigger.

-- Only touch updatedAt if the UPDATE did not set it explicitly. A row-level
-- UPDATE that specifies "updatedAt" (e.g. a data migration preserving the
-- original timestamp) will have NEW != OLD, and we leave that value alone.
--
-- Edge case: `UPDATE ... SET "updatedAt" = OLD."updatedAt"` is treated as if
-- the column was not set — NEW matches OLD so the trigger advances to now().
-- A data migration intending to preserve the exact original timestamp must
-- `ALTER TABLE ... DISABLE TRIGGER <name>` for the duration of the backfill.
CREATE OR REPLACE FUNCTION public.set_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."updatedAt" IS NOT DISTINCT FROM OLD."updatedAt" THEN
    NEW."updatedAt" = now();
  END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  r RECORD;
BEGIN
  -- uuid id columns that are PRIMARY KEYs → gen_random_uuid().
  -- Restricted to PKs to avoid ever touching a non-PK "id" column
  -- (unusual but possible). In this schema every public."id" column
  -- is a PK, so the PK filter is purely defensive.
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.table_constraints tc
      ON tc.table_schema = c.table_schema
     AND tc.table_name = c.table_name
     AND tc.constraint_type = 'PRIMARY KEY'
    JOIN information_schema.key_column_usage kcu
      ON kcu.constraint_schema = tc.constraint_schema
     AND kcu.constraint_name = tc.constraint_name
     AND kcu.table_name = tc.table_name
     AND kcu.column_name = c.column_name
    WHERE c.table_schema = 'public'
      AND c.column_name = 'id'
      AND c.data_type = 'uuid'
      AND c.column_default IS NULL
  LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT gen_random_uuid()',
      r.table_name
    );
  END LOOP;

  -- createdAt timestamps → now()
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.column_name = 'createdAt'
      AND c.data_type IN ('timestamp with time zone', 'timestamp without time zone')
      AND c.column_default IS NULL
  LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ALTER COLUMN "createdAt" SET DEFAULT now()',
      r.table_name
    );
  END LOOP;

  -- updatedAt timestamps → now()
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.column_name = 'updatedAt'
      AND c.data_type IN ('timestamp with time zone', 'timestamp without time zone')
      AND c.column_default IS NULL
  LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ALTER COLUMN "updatedAt" SET DEFAULT now()',
      r.table_name
    );
  END LOOP;
END $$;

-- Auto-touch updatedAt on every UPDATE.
DO $$
DECLARE
  r RECORD;
  trig_name TEXT;
BEGIN
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.column_name = 'updatedAt'
  LOOP
    trig_name := format('set_updated_at_%s', r.table_name);
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', trig_name, r.table_name);
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column()',
      trig_name, r.table_name
    );
  END LOOP;
END $$;
