-- This migration is intentionally a no-op.
--
-- The xeroPushInProgress column was consolidated into
-- 20260421160000_xero_cleanup_required.sql to ensure both columns
-- (xeroCleanupRequired and xeroPushInProgress) are added atomically in
-- the same migration deployment. Splitting them created a window where
-- xero-sync.ts's atomic UPDATE (which conditions on both columns) would
-- fail because the second column didn't yet exist.
