-- Backfill missing column defaults for every table in `public`.
--
-- Schema was originally generated by Prisma, which produced identifiers and
-- timestamps at the application layer. After migrating to direct Supabase
-- JS inserts (no ORM), rows omitting `id` / `createdAt` / `updatedAt` fail
-- with NOT NULL violations. This migration:
--   1. Sets `DEFAULT gen_random_uuid()` on every uuid `id` PK column that has
--      no default.
--   2. Sets `DEFAULT now()` on every `createdAt` / `updatedAt` timestamp
--      column that has no default.
--   3. Installs a BEFORE UPDATE trigger on every table with an `updatedAt`
--      column so it auto-advances on writes.
--
-- Idempotent: re-running only targets columns still missing a default and
-- drops+recreates the trigger.

CREATE OR REPLACE FUNCTION public.set_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  r RECORD;
BEGIN
  -- uuid id columns → gen_random_uuid()
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.column_name = 'id'
      AND c.data_type = 'uuid'
      AND c.column_default IS NULL
  LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT gen_random_uuid()',
      r.table_name
    );
  END LOOP;

  -- createdAt timestamps → now()
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.column_name = 'createdAt'
      AND c.data_type IN ('timestamp with time zone', 'timestamp without time zone')
      AND c.column_default IS NULL
  LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ALTER COLUMN "createdAt" SET DEFAULT now()',
      r.table_name
    );
  END LOOP;

  -- updatedAt timestamps → now()
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.column_name = 'updatedAt'
      AND c.data_type IN ('timestamp with time zone', 'timestamp without time zone')
      AND c.column_default IS NULL
  LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ALTER COLUMN "updatedAt" SET DEFAULT now()',
      r.table_name
    );
  END LOOP;
END $$;

-- Auto-touch updatedAt on every UPDATE.
DO $$
DECLARE
  r RECORD;
  trig_name TEXT;
BEGIN
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.column_name = 'updatedAt'
  LOOP
    trig_name := format('set_updated_at_%s', r.table_name);
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', trig_name, r.table_name);
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column()',
      trig_name, r.table_name
    );
  END LOOP;
END $$;
