ALTER TABLE "Talent"
  ADD COLUMN IF NOT EXISTS "businessType" TEXT NOT NULL DEFAULT 'SELF_EMPLOYED',
  ADD COLUMN IF NOT EXISTS "companyName" TEXT,
  ADD COLUMN IF NOT EXISTS "companyRegNumber" TEXT,
  ADD COLUMN IF NOT EXISTS "registeredAddress" TEXT;
